version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pythondb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URI: mysql+pymysql://admin:admin@db/pythondb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8000:80"
    depends_on:
      - db

volumes:
  db_data:







